name: default
version: "1.0"
description: "Default rubric with security and correctness rules"
rules:
  # Security rules (critical)
  - id: DEF-001
    name: no_hardcoded_credentials
    category: security
    severity: critical
    description: "No hardcoded passwords or credentials"
    patterns:
      - "password\\s*=\\s*[\"'][^\"']{4,}[\"']"
      - "passwd\\s*=\\s*[\"'][^\"']+[\"']"
    exceptions:
      - "*_test.py"
      - "test_*.py"
      - "**/tests/**"

  # Correctness rules (high)
  - id: DEF-002
    name: no_bare_except
    category: correctness
    severity: high
    description: "Avoid bare except clauses"
    patterns:
      - "except\\s*:"
    exceptions:
      - "*_test.py"

  - id: DEF-003
    name: no_mutable_default_args
    category: correctness
    severity: medium
    description: "Avoid mutable default arguments"
    patterns:
      - "def\\s+\\w+\\([^)]*=\\s*\\[\\]"
      - "def\\s+\\w+\\([^)]*=\\s*\\{\\}"
    exceptions: []

  # Performance rules (medium)
  - id: DEF-004
    name: no_nested_loops_o_n_squared
    category: performance
    severity: medium
    description: "Potential O(n^2) nested loops"
    patterns:
      - "for\\s+\\w+\\s+in[^:]+:\\s*\\n\\s+for\\s+\\w+\\s+in"
    exceptions:
      - "*_test.py"

  # Code quality (low)
  - id: DEF-005
    name: no_print_statements
    category: correctness
    severity: low
    description: "Avoid print statements in production"
    patterns:
      - "^\\s*print\\("
    exceptions:
      - "*_test.py"
      - "test_*.py"
      - "**/tests/**"
      - "cli.py"
      - "__main__.py"
